// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.


function fib(n,sum,a,b){
  
  if(a>n){
    return sum
  }
  
  let t=a
  a=b
  b=t+b
  
  if(a%2==0){
    sum+=a
  }
  
  return fib(n,sum,a,b)
}

function fiboEvenSum(n) {
  return fib(n,0,1,2)
}

fiboEvenSum(10)
